# Generated by Django 4.1.7 on 2023-05-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sid", models.IntegerField()),
                ("Sname", models.CharField(max_length=100)),
                ("Sage", models.IntegerField()),
                ("Sstate", models.CharField(max_length=100)),
            ],
        ),
    ]
